// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaMF5xWbvclSbCy5nJ0GHBfcVfOOTezQc',
    appId: '1:880906643702:android:ea542503dda67111b5a4d7',
    messagingSenderId: '880906643702',
    projectId: 'app-lectura-7f4af',
    storageBucket: 'app-lectura-7f4af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2cEbkPXr31fWiQsijx0QStqfpmr2rczQ',
    appId: '1:880906643702:ios:5bab29d27f70181bb5a4d7',
    messagingSenderId: '880906643702',
    projectId: 'app-lectura-7f4af',
    storageBucket: 'app-lectura-7f4af.firebasestorage.app',
    androidClientId: '880906643702-2hhmcpnsqtbveu0gcrblv34gu5f67g24.apps.googleusercontent.com',
    iosClientId: '880906643702-qprvu5rjre5kanb35p3g3970ra16u282.apps.googleusercontent.com',
    iosBundleId: 'com.example.lecturaApp',
  );
}
